### ISSUE TITLE
Terminate & regenerate HAProxy

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe-build-infrastructure#83]
As per communication from AWS, this must be done before 2019-06-24 19:00 UTC

**Comment by S-Coyle** [comment]
Tested on staging and after terminating proxy on AWS I was able to run terraform again to recreate it, then run provisioning again - this brought staging Jenkins back online.
**Note** there was an issue then connecting the Windows slaves to Jenkins - error received during provisioning when trying to start the slave service. Suspect that this is a general error that will always be received when re-provisioning, and not because of the new proxy. Can be confirmed if required.

**Comment by jacderida** [comment]
I can definitely confirm now that the issue with the Windows slaves occurs on a re-provision of the environment and is nothing to do with the proxy.

**Comment by jacderida** [comment]
This was done by terminating the instance, re-running Terraform, then re-provisioning. Went without incident.
